#!/usr/bin/env bash
# Display some information about CName

funct()
{
    a_record=$(dig "$1"."$2" | grep -A1 'ANSWER SECTION:' | awk '{print $4}' | tr -d '\n')
    ip_add=$(dig "$1"."$2" | grep -A1 'ANSWER SECTION:' | awk '{print $5}' | tr -d '\n')
    echo "The subdomain $1 is a $a_record record and points to $ip_add"
}
subdomain="www lib-01 web-01 web-02"
if (( $# == 1))
then
    for item in $subdomain
    do
        funct "$item" "$1"
    done
elif (( $# == 2 ))
then
    funct "$2" "$1"
fi
