#!/usr/bin/env bash
# redirect some file
rd_cmd="error_page  404              /404.html;
   location = /404.html {
        root /usr/share/nginx/html;
   }"
file="/etc/nginx/conf.d/default.conf"
sed -i "s/'error_page  404              /404.html;'/$rd_cmd/" "$file"
