#!/usr/bin/env bash
# web-02 to be identical to web-01

hostname=$(hostname)

printf %s "server{
    listen 80;
    server_name localhost;

    add_header X-Served-By $hostname;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
    }
}
" >> /etc/nginx/sites-available/default

sudo systemctl reload nginx