#!/usr/bin/env bash
# web-02 to be identical to web-01
sudo apt-get update
sudo apt-get install nginx -y

hostname=$(hostname)

printf %s "server{
    listen 80;
    server_name localhost;

    add_header X-Served-By $hostname;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
    }
}
" >> /etc/nginx/sites-available/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

sudo rm /etc/nginx/sites-enabled/default

sudo systemctl reload nginx