#!/usr/bin/env bash
# This script is displaying "Best school" at 10 times,
# but the 9th iterations displays "Best School" and the "Hi"
str="Best School"
i=1
while [ $i -le 10 ]
do
    if [ $i -eq 9 ]
    then
        echo "$str";echo "Hi"
    else
        echo "$str"
    fi
    i=$(( i + 1 ))
done