#!/usr/bin/env bash
# This script is displaying form 1 to 10
# "bad luck" for the 4th iteration
# "good luck" for the 9th iteration
# "Best School" for the others iterations
str="Best School"
i=1
while [ $i -le 10 ]
do
    if [ $i -eq 4 ]
    then
        echo "bad luck"
    elif [ $i -eq 8 ]
    then
        echo "good luck"
    else
        echo "$str"
    fi
    i=$(( i + 1 ))
done