#!/usr/bin/env bash
# This script is displaying from 1 to 20
# "4 and then bad luck from the China"
# "9 and then bad luck from the Japan"
# "17 and then bad luck from the Italy"
i=1
while [ $i -le 20 ]
do
    case $i in 4)
        echo "$i";echo "bad luck from China";;
        9)
        echo "$i";echo "bad luck from Japan";;
        17)
        echo "$i";echo "bad luck from Italy";;
        *)
        echo "$i";;
        esac
    i=$(( i + 1 ))
done