#!/usr/bin/env bash
# This script gives an information for the school file
file="school"
if [ -e $file ]
then
    echo "$file file exists"
    if [ ! -s $file ]
    then
        echo "$file is empty"
    else
        echo "$file is not empty"
    fi
    if [ -f $file ]
    then
        echo "$file is a regular file"
    fi
else
    echo "$file file does not exist"
fi
