#!/usr/bin/env bash

# Update the package index
sudo apt-get update


# Create an nginx user if it doesn't exist
if ! id -u nginx &>/dev/null; then
    adduser --system --no-create-home --disabled-login --group nginx
fi

# Install Nginx
sudo apt-get install -y nginx

# Backup the default Nginx configuration file
sudo mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak

# Create a new Nginx configuration file
cat <<EOF > /etc/nginx/nginx.conf
user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /var/run/nginx.pid;

events {
    worker_connections 768;
    # Other event configurations if needed
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format main '\$remote_addr - \$remote_user [\$time_local] "\$request" '
                      '\$status \$body_bytes_sent "\$http_referer" '
                      '"\$http_user_agent" "\$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/sites-enabled/*;

    server {
        listen 8080 default_server;
        listen [::]:8080 default_server;

        root /var/www/html;
        index index.html index.htm;

        server_name _;

        location / {
            try_files \$uri \$uri/ =404;
        }
    }
}
EOF

# Restart Nginx to apply the changes
sudo systemctl restart nginx
